apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: backend-users
spec:
  replicas: 1
  template:  
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        name: backend-users
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - backend-users
      from:
        kind: ImageStreamTag
        name: backend-users:latest
    type: ImageChange
